import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackButtonHandler from "@/components/BackButtonHandler"; // Import the back button handler
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import DataCheck from "@/components/DataCheck";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vansh App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DataCheck/>
        <BackButtonHandler /> {/* Add this here */}
        {children}
      </body>
    </html>
  );
}
